# Generated by Django 5.0.3 on 2024-04-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_author_alter_maqola_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='author',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='maqola',
            name='tag',
            field=models.CharField(choices=[('world', 'world'), ('local', 'local'), ('sport', 'sport')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
